app/base/models.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask_login import UserMixin
from sqlalchemy import LargeBinary, Column, Integer, String

from app import db, login_manager

from app.base.util import hash_pass

class User(db.Model, UserMixin):

    __tablename__ = 'User'

    id = Column(Integer, primary_key=True)
    username = Column(String, unique=True)
    email = Column(String, unique=True)
    password = Column(LargeBinary)

    def __init__(self, **kwargs):
        for property, value in kwargs.items():
            # depending on whether value is an iterable or not, we must
            # unpack it's value (when **kwargs is request.form, some values
            # will be a 1-element list)
            if hasattr(value, '__iter__') and not isinstance(value, str):
                # the ,= unpack of a singleton fails PEP8 (travis flake8 test)
                value = value[0]

            if property == 'password':
                value = hash_pass( value ) # we need bytes here (not plain str)
                
            setattr(self, property, value)

    def __repr__(self):
        return str(self.username)


@login_manager.user_loader
def user_loader(id):
    return User.query.filter_by(id=id).first()

@login_manager.request_loader
def request_loader(request):
    username = request.form.get('username')
    user = User.query.filter_by(username=username).first()
    return user if user else None

app/base/forms.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import InputRequired, Email, DataRequired

## login and registration

class LoginForm(FlaskForm):
    username = StringField    ('Username', id='username_login'   , validators=[DataRequired()])
    password = PasswordField('Password', id='pwd_login'        , validators=[DataRequired()])

class CreateAccountForm(FlaskForm):
    username = StringField('Username'     , id='username_create' , validators=[DataRequired()])
    email    = StringField('Email'        , id='email_create'    , validators=[DataRequired(), Email()])
    password = PasswordField('Password' , id='pwd_create'      , validators=[DataRequired()])

app/base/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'base_blueprint',
    __name__,
    url_prefix='',
    template_folder='templates',
    static_folder='static'
)

app/base/routes.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import jsonify, render_template, redirect, request, url_for
from flask_login import (
    current_user,
    login_required,
    login_user,
    logout_user
)

from app import db, login_manager
from app.base import blueprint
from app.base.forms import LoginForm, CreateAccountForm
from app.base.models import User

from app.base.util import verify_pass

@blueprint.route('/')
def route_default():
    return redirect(url_for('base_blueprint.login'))

## Login & Registration

@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm(request.form)
    if 'login' in request.form:
        
        # read form data
        username = request.form['username']
        password = request.form['password']

        # Locate user
        user = User.query.filter_by(username=username).first()
        
        # Check the password
        if user and verify_pass( password, user.password):

            login_user(user)
            return redirect(url_for('base_blueprint.route_default'))

        # Something (user or pass) is not ok
        return render_template( 'accounts/login.html', msg='Wrong user or password', form=login_form)

    if not current_user.is_authenticated:
        return render_template( 'accounts/login.html',
                                form=login_form)
    return redirect(url_for('home_blueprint.index'))

@blueprint.route('/register', methods=['GET', 'POST'])
def register():
    login_form = LoginForm(request.form)
    create_account_form = CreateAccountForm(request.form)
    if 'register' in request.form:

        username  = request.form['username']
        email     = request.form['email'   ]

        # Check usename exists
        user = User.query.filter_by(username=username).first()
        if user:
            return render_template( 'accounts/register.html', 
                                    msg='Username already registered',
                                    success=False,
                                    form=create_account_form)

        # Check email exists
        user = User.query.filter_by(email=email).first()
        if user:
            return render_template( 'accounts/register.html', 
                                    msg='Email already registered', 
                                    success=False,
                                    form=create_account_form)

        # else we can create the user
        user = User(**request.form)
        db.session.add(user)
        db.session.commit()

        return render_template( 'accounts/register.html', 
                                msg='User created please <a href="/login">login</a>', 
                                success=True,
                                form=create_account_form)

    else:
        return render_template( 'accounts/register.html', form=create_account_form)

@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('base_blueprint.login'))

## Errors

@login_manager.unauthorized_handler
def unauthorized_handler():
    return render_template('page-403.html'), 403

@blueprint.errorhandler(403)
def access_forbidden(error):
    return render_template('page-403.html'), 403

@blueprint.errorhandler(404)
def not_found_error(error):
    return render_template('page-404.html'), 404

@blueprint.errorhandler(500)
def internal_error(error):
    return render_template('page-500.html'), 500

app/base/templates/accounts/login.html
{% extends "layouts/base.html" %}

{% block title %} Login {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="panel-header panel-header-sm">
    </div>
    <div class="content">
        <div class="row">
            <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <h5 class="title">Login</h5>
                    <span>
                        {% if msg %}
                            {{ msg | safe }}
                        {% else %}
                            Add your credentials
                        {% endif %}
                    </span>                    
                </div>

                <br />
                <div class="card-body">

                    <form role="form" method="post" action="">

                        {{ form.hidden_tag() }}

                        <div class="row">

                            <div class="col-md-2 pr-1">
                                <div class="form-group">
                                    <label>Username</label>
                                </div>
                            </div>

                            <div class="col-md-6 pr-1">
                                <div class="form-group">
                                    {{ form.username(placeholder="Username", class="form-control") }}
                                </div>
                            </div>

                        </div>

                        <div class="row">

                            <div class="col-md-2 pr-1">
                                <div class="form-group">
                                    <label>Password</label>
                                </div>
                            </div>

                            <div class="col-md-6 pr-1">
                                <div class="form-group">
                                    {{ form.password(placeholder="Password", class="form-control", type="password") }}
                                </div>
                            </div>

                        </div>

                        <br />
                        
                        <div class="row">

                            <div class="col-md-2 pr-1"></div>
                            <div class="col-md-5 pr-1">
                                <button type="submit" name="login" class="btn btn-fill btn-primary">Log in</button>
                                &nbsp;&nbsp; or &nbsp; <a href="{{ url_for('base_blueprint.register') }}" >Register</a>
                            </div>

                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

app/base/templates/accounts/register.html
{% extends "layouts/base.html" %}

{% block title %} Register {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="panel-header panel-header-sm">
    </div>
    <div class="content">
        <div class="row">
            <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <h5 class="title">Register</h5>
                    <span>
                        {% if msg %}
                            {{ msg | safe }}
                        {% else %}
                            Add your credentials
                        {% endif %}
                    </span>                    
                </div>

                <br />
                <div class="card-body">

                    <form role="form" method="post" action="">

                        {{ form.hidden_tag() }}

                        <div class="row">
                            <div class="col-md-2 pr-1">
                                <div class="form-group">
                                    <label>Username</label>
                                </div>
                            </div>
                            <div class="col-md-6 pr-1">
                                <div class="form-group">
                                    {{ form.username(placeholder="Username", class="form-control") }}
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-2 pr-1">
                                <div class="form-group">
                                    <label>Email</label>
                                </div>
                            </div>
                            <div class="col-md-6 pr-1">
                                <div class="form-group">
                                    {{ form.email(placeholder="Email", class="input form-control", type="email") }}
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-2 pr-1">
                                <div class="form-group">
                                    <label>Password</label>
                                </div>
                            </div>
                            <div class="col-md-6 pr-1">
                                <div class="form-group">
                                    {{ form.password(placeholder="Password", class="form-control", type="password") }}
                                </div>
                            </div>
                        </div>

                        <br />
                        
                        <div class="row">

                            <div class="col-md-2 pr-1"></div>
                            <div class="col-md-5 pr-1">
                                <button type="submit" name="register" class="btn btn-fill btn-primary">Register</button>
                                &nbsp;&nbsp; or &nbsp; <a href="{{ url_for('base_blueprint.login') }}" >Login</a>
                            </div>

                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

app/base/templates/includes/footer.html
<footer class="footer">
    <div class=" container-fluid ">
      <nav>
        <ul>
          <li>
            <a target="_blank" 
               href="https://www.plus.ac.at/biowissenschaften/der-fachbereich/arbeitsgruppen/lepperdinger/spoc-labs/">
              SPOC labs
            </a>
          </li>
        </ul>
      </nav>
      <!-- <div class="copyright" id="copyright">
        &copy; <a href="https://bit.ly/3fKQZaL" target="_blank">Creative Tim</a> 
        - coded by <a href="https://appseed.us" target="_blank">AppSeed</a>.
      </div> -->
    </div>
</footer>

app/base/templates/includes/navigation.html
      <nav class="navbar navbar-expand-lg navbar-transparent  bg-primary  navbar-absolute">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <div class="navbar-toggle">
              <button type="button" class="navbar-toggler">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </button>
            </div>
            <a class="navbar-brand" href="#currently_unused">Dashboard</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end" id="navigation">

            {% if current_user.is_authenticated %}
            <form>
              <div class="input-group no-border">
                <input type="text" value="" class="form-control" placeholder="Search...">
                <div class="input-group-append">
                  <div class="input-group-text">
                    <i class="now-ui-icons ui-1_zoom-bold"></i>
                  </div>
                </div>
              </div>
            </form>
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="#currently_unused">
                  <i class="now-ui-icons media-2_sound-wave"></i>
                  <p>
                    <span class="d-lg-none d-md-block">Stats</span>
                  </p>
                </a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="now-ui-icons location_world"></i>
                  <p>
                    <span class="d-lg-none d-md-block">Some Actions</span>
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="/experiments">Create new Experiment</a>
                  <a class="dropdown-item" href="/experiment/default">Set Experiment: default</a>
                  <!-- <a class="dropdown-item" href="#">Something else here</a> -->
                </div>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/user.html">
                  <i class="now-ui-icons users_single-02"></i>
                  <p>
                    <span class="d-lg-none d-md-block">Account</span>
                  </p>
                </a>
              </li>
            </ul>
            {% endif %}
          </div>
        </div>
      </nav>
   

app/base/templates/includes/scripts.html
  <!--   Core JS Files   -->
  <script src="/static/assets/js/core/jquery.min.js"></script>
  <script src="/static/assets/js/core/popper.min.js"></script>
  <script src="/static/assets/js/core/bootstrap.min.js"></script>
  <script src="/static/assets/js/plugins/perfect-scrollbar.jquery.min.js"></script>
  <!--  Notifications Plugin    -->
  <script src="/static/assets/js/plugins/bootstrap-notify.js"></script>
  <!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="/static/assets/js/now-ui-dashboard.min.js?v=1.5.0" type="text/javascript"></script><!-- Now Ui Dashboard DEMO methods, don't include it in your project! -->
  <script src="/static/assets/demo/demo.js"></script>

app/base/templates/includes/sidebar.html
<!-- data-color = "#005A3B" -->
<div class="sidebar" data-color="green">
    <!--
      Tip 1: You can change the color of the sidebar using: data-color="blue | green | orange | red | yellow"
  -->
    <div class="logo">
      <a target="_blank"
         href="https://appseed.us/admin-dashboards/flask-now-ui-dashboard" 
         class="simple-text logo-mini">
        SPOC lab
      </a>
      <a target="_blank" 
         href="https://appseed.us/admin-dashboards/flask-now-ui-dashboard" 
         class="simple-text logo-normal">
        het-cam
      </a>
    </div>
    <div class="sidebar-wrapper" id="sidebar-wrapper">
      <ul class="nav">
      {% if current_user.is_authenticated %}
        <li class="{% if segment is defined %}{% if 'index' in segment %} active {% endif %}{% endif %}">
          <a href="/">
            <i class="now-ui-icons media-1_camera-compact"></i>
            <p>HET CAM²</p>
          </a>
        </li>
        <li class="{% if segment is defined %}{% if 'gallery' in segment %} active {% endif %}{% endif %}">
          <a href="/gallery">
            <i class="now-ui-icons design_image"></i>
            <p>Recorded Images</p>
          </a>
        </li>
        <li class="{% if segment is defined %}{% if 'skeleton' in segment %} active {% endif %}{% endif %}">
          <a href="/gallery-skeleton">
            <i class="now-ui-icons design_image"></i>
            <p>Skeletonized Images</p>
          </a>
        </li>
        <li class="{% if segment is defined %}{% if 'yolo' in segment %} active {% endif %}{% endif %}">
          <a href="/gallery-yolo">
            <i class="now-ui-icons design_image"></i>
            <p>Yolov5 object detection</p>
          </a>
        </li>        
        <li class="{% if segment is defined %}{% if 'experiments' in segment %} active {% endif %}{% endif %}">
          <a href="/experiments">
            <i class="now-ui-icons education_atom"></i>
            <p>Experiments</p>
          </a>
        </li>
        <li class="{% if segment is defined %}{% if 'camera-settings' in segment %} active {% endif %}{% endif %}">
          <a href="/camera-settings">
            <i class="now-ui-icons ui-1_settings-gear-63"></i>
            <p>Camera</p>
          </a>
        </li>
        {#
        <!-- <li class="{% if 'dashboard' in segment %} active {% endif %}">
          <a href="/dashboard.html">
            <i class="now-ui-icons education_atom"></i>
            <p>Dashboard</p>
          </a>
        </li> -->
        <!-- <li class="{% if 'user' in segment %} active {% endif %}">
          <a href="/user.html">
            <i class="now-ui-icons users_single-02"></i>
            <p>User Profile</p>
          </a>
        </li>
        <li class="{% if 'icons' in segment %} active {% endif %}">
          <a href="/icons.html">
            <i class="now-ui-icons design_app location_map-big"></i>
            <p>Icons</p>
          </a>
        </li>
        <li class="{% if 'notifications' in segment %} active {% endif %}">
          <a href="/notifications.html">
            <i class="now-ui-icons ui-1_bell-53"></i>
            <i class="now-ui-icons loader_gear"></i>
            <p>Notifications</p>
          </a>
        </li>
        <li class="{% if 'tables' in segment %} active {% endif %}">
          <a href="/tables.html">
            <i class="now-ui-icons design_bullet-list-67"></i>
            <p>Table List</p>
          </a>
        </li>
        <li class="{% if 'typography' in segment %} active {% endif %}">
          <a href="/typography.html">
            <i class="now-ui-icons text_caps-small"></i>
            <p>Typography</p>
          </a>
        </li> -->
        <!-- <li class="{% if 'page-blank' in segment %} active {% endif %}">
            <a href="/page-blank.html">
                <i class="now-ui-icons text_caps-small"></i>
                <p>Blank Page</p>
            </a>
        </li>
        <li class="{% if 'page-404' in segment %} active {% endif %}">
            <a href="/page-404.html">
                <i class="now-ui-icons loader_gear"></i>
                <p>Error 404</p>
            </a>
        </li>         -->
        #}
        <li class="">
            <a href="{{ url_for('base_blueprint.logout') }}">
                <i class="now-ui-icons media-1_button-power"></i>
                <p>Logout</p>
            </a>
        </li>         
        <li class="active">
          <a target="_blank"
             href="https://www.plus.ac.at/biowissenschaften/der-fachbereich/arbeitsgruppen/lepperdinger/spoc-labs/">
            <i class="now-ui-icons objects_spaceship"></i>
            <p>SPOC lab PLUS</p>
          </a>
        </li>
        {% else %}
        <li class="">
          <a href="/login">
            <i class="now-ui-icons design_image"></i>
            <p>Login</p>
          </a>
        </li>
        <li class="active">
          <a href="/gallery">
            <i class="now-ui-icons design_image"></i>
            <p>Recorded Images</p>
          </a>
        </li>
        <li class="">
          <a target="_blank"
             href="https://www.plus.ac.at/biowissenschaften/der-fachbereich/arbeitsgruppen/lepperdinger/spoc-labs/">
            <i class="now-ui-icons objects_spaceship"></i>
            <p>SPOC lab PLUS</p>
          </a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>

app/base/templates/layouts/base-fullscreen.html
<!-- NOT_IMPLEMENTED -->

app/base/templates/layouts/base.html
<!--

=========================================================
* Now UI Dashboard - v1.5.0
=========================================================

* Product Page: https://www.creative-tim.com/product/now-ui-dashboard
* Copyright 2019 Creative Tim (http://www.creative-tim.com)

* Designed by www.invisionapp.com Coded by www.creative-tim.com

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

-->
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="/static/assets/img/apple-icon.png">
  <link rel="icon" type="image/png" href="/static/assets/img/favicon.png">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <link rel="canonical" href="https://appseed.us/admin-dashboards/flask-dashboard-now-ui-pro">

  <title>
    SPOC HET-CAM webcam - {% block title %}{% endblock %} | SPOC lab
  </title>

  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  <!-- CSS Files -->
  <link href="/static/assets/css/bootstrap.min.css" rel="stylesheet" />
  <link href="/static/assets/css/now-ui-dashboard.css?v=1.5.0" rel="stylesheet" />
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link href="/static/assets/demo/demo.css" rel="stylesheet" />

  <!-- Specific Page CSS goes HERE  -->
  {% block stylesheets %}{% endblock stylesheets %}

</head>

<body class="">
  <div class="wrapper ">
    
    {% include 'includes/sidebar.html' %}

    <div class="main-panel" id="main-panel">

      {% include 'includes/navigation.html' %}

      {% block content %}{% endblock content %}

      {% include 'includes/footer.html' %}

    </div>
  </div>

  {% include 'includes/scripts.html' %}

  <!-- Specific Page JS goes HERE  -->
  {% block javascripts %}{% endblock javascripts %}

</body>
</html>